from __future__ import annotations

from pathlib import Path

from app.adapters.ffmpeg_adapter import FFmpegError, run_ffmpeg
from app.modules.timeline_builder.timeline_builder import ClipType, TimelineClip
from app.utils.logger import get_logger

logger = get_logger(__name__)


class SpecialClipRenderer:
    """
    Handles rendering of FREEZE and FREEZE_ZOOM clips generated by SESE.

    - ClipType.FREEZE: loops a single frame for the clip duration (freeze frame effect).
    - ClipType.FREEZE_ZOOM: loops a single frame with a slow zoompan push-in (Ken Burns style).
    """

    @staticmethod
    def render(
        clip: TimelineClip,
        output_path: Path,
        width: int,
        height: int,
        fps: int,
        grain: int,
    ) -> None:
        """
        Render a special clip (FREEZE or FREEZE_ZOOM) to output_path.
        Fallback chain: FREEZE_ZOOM → FREEZE → black clip
        """
        if clip.clip_type == ClipType.FREEZE_ZOOM:
            try:
                SpecialClipRenderer._render_freeze_zoom(clip, output_path, width, height, fps, grain)
                return
            except FFmpegError as exc:
                logger.warning(
                    f"[SpecialClipRenderer] FREEZE_ZOOM failed, falling back to FREEZE. "
                    f"clip={clip.source_path}@{clip.start:.3f}s, error={exc}"
                )

        # FREEZE (or fallback from FREEZE_ZOOM)
        try:
            SpecialClipRenderer._render_freeze(clip, output_path, width, height, fps, grain)
            return
        except FFmpegError as exc:
            logger.warning(
                f"[SpecialClipRenderer] FREEZE failed, falling back to black clip. "
                f"clip={clip.source_path}@{clip.start:.3f}s, error={exc}"
            )

        # Final fallback: generate a solid black video segment
        SpecialClipRenderer._render_black_fallback(output_path, width, height, fps, clip.duration)

    @staticmethod
    def _render_freeze(
        clip: TimelineClip,
        output_path: Path,
        width: int,
        height: int,
        fps: int,
        grain: int,
    ) -> None:
        """Render a freeze-frame clip: extract one frame, loop it for the full duration."""
        duration = round(clip.duration, 3)
        grain_filter = f",noise=alls={grain}:allf=t+u" if grain > 0 else ""
        vf = (
            f"scale={width}:{height}:force_original_aspect_ratio=decrease,"
            f"pad={width}:{height}:(ow-iw)/2:(oh-ih)/2,"
            f"format=yuv420p"
            f"{grain_filter}"
        )
        run_ffmpeg(
            [
                "-y",
                "-ss",
                f"{clip.start:.3f}",
                "-t",
                "0.1",                   # extract a tiny segment around freeze point
                "-i",
                clip.source_path,
                "-vf",
                f"trim=0:0.033,{vf}",   # keep single frame, loop below
                "-loop",
                "1",                     # loop the single frame
                "-t",
                f"{duration:.3f}",
                "-an",
                "-c:v",
                "libx264",
                "-preset",
                "veryfast",
                "-crf",
                "23",
                "-pix_fmt",
                "yuv420p",
                "-r",
                str(fps),
                str(output_path),
            ]
        )

    @staticmethod
    def _render_freeze_zoom(
        clip: TimelineClip,
        output_path: Path,
        width: int,
        height: int,
        fps: int,
        grain: int,
    ) -> None:
        """
        Render a freeze-zoom clip: extract a single frame, apply zoompan for a slow Ken Burns
        push-in effect.  The zoom goes from 1.0 to ~1.05 over the clip duration.
        """
        duration = round(clip.duration, 3)
        total_frames = max(1, round(duration * fps))
        # Zoom from 1.00 → 1.05 smoothly; zoom step per frame
        # zoompan expression: z=min(zoom+0.0005,1.05)  (slow zoom)
        grain_filter = f",noise=alls={grain}:allf=t+u" if grain > 0 else ""
        zoompan_filter = (
            f"zoompan=z='min(zoom+0.0003,1.05)':d={total_frames}"
            f":x='iw/2-(iw/zoom/2)':y='ih/2-(ih/zoom/2)'"
            f":s={width}x{height}:fps={fps}"
        )
        vf = (
            f"scale={width * 2}:{height * 2}:force_original_aspect_ratio=decrease,"
            f"pad={width * 2}:{height * 2}:(ow-iw)/2:(oh-ih)/2,"
            f"{zoompan_filter},"
            f"format=yuv420p"
            f"{grain_filter}"
        )
        run_ffmpeg(
            [
                "-y",
                "-ss",
                f"{clip.start:.3f}",
                "-t",
                "0.1",
                "-i",
                clip.source_path,
                "-vf",
                f"trim=0:0.033,{vf}",
                "-loop",
                "1",
                "-t",
                f"{duration:.3f}",
                "-an",
                "-c:v",
                "libx264",
                "-preset",
                "veryfast",
                "-crf",
                "23",
                "-pix_fmt",
                "yuv420p",
                "-r",
                str(fps),
                str(output_path),
            ]
        )

    @staticmethod
    def _render_black_fallback(
        output_path: Path,
        width: int,
        height: int,
        fps: int,
        duration: float,
    ) -> None:
        """
        Last-resort fallback: generate a solid black video segment.
        Uses ffmpeg lavfi color source — requires no input file.
        Always succeeds as long as FFmpeg is installed.
        """
        logger.warning(
            f"[SpecialClipRenderer] Generating black fallback clip "
            f"({width}x{height}, {duration:.3f}s) → {output_path}"
        )
        run_ffmpeg(
            [
                "-y",
                "-f",
                "lavfi",
                "-i",
                f"color=c=black:s={width}x{height}:r={fps}",
                "-t",
                f"{round(duration, 3):.3f}",
                "-an",
                "-c:v",
                "libx264",
                "-preset",
                "veryfast",
                "-crf",
                "23",
                "-pix_fmt",
                "yuv420p",
                str(output_path),
            ]
        )
