import type { DouyinReupSettings } from '../../types/project';

export const DEFAULT_REVIEW_RENDER_SETTINGS: DouyinReupSettings = {
  enabled: true, preset_id: 'safe_review', preset_name: 'Safe Review', source_language: 'zh', target_language: 'vi',
  translation_style: 'sat_nghia_troi_chay', subtitle_position: 'bottom_overlay', translation_provider: 'gemini',
  subtitle_source_priority: ['sidecar_srt', 'embedded_subtitle', 'asr', 'ocr_hardsub'], use_sidecar_srt: true,
  use_embedded_subtitle: true, use_asr_if_no_subtitle: true, asr_provider: 'faster_whisper', asr_model_size: 'medium',
  asr_device: 'auto', asr_vad_filter: false, asr_max_audio_seconds: 180, asr_subprocess_isolation: true,
  asr_timeout_seconds: 1200, asr_subtitle_offset_seconds: -0.25, use_ocr_if_asr_failed: true,
  use_ocr_if_no_subtitle: true, ocr_provider: 'easyocr', ocr_language: 'ch', ocr_sample_fps: 2,
  ocr_subprocess_isolation: true, ocr_timeout_seconds: 1200, ocr_region_mode: 'bottom_auto',
  ocr_manual_region: null, ocr_min_confidence: 0.35, ocr_dedupe_similarity: 0.86,
  ocr_min_text_length: 2, ocr_merge_gap_ms: 600, ocr_min_duration_ms: 500, ocr_max_duration_ms: 6000,
  ocr_filter_watermarks: true, ocr_watermark_terms: [],
  prefer_ocr_over_asr_when_text_visible: false, visual_style_preset_id: 'clean_review_light', burn_subtitle: true,
  add_overlay: false, overlay_mode: 'none', custom_overlay_path: 'examples/overlay',
  custom_overlay_height_percent: 100, custom_overlay_fit_mode: 'cover',
  subtitle_style_custom_enabled: false, subtitle_font_family: 'Arial', subtitle_font_size: 54,
  subtitle_font_color: '#FFFFFF', subtitle_stroke_color: '#000000', subtitle_stroke_width: 2,
  subtitle_shadow_enabled: true, subtitle_shadow_color: '#000000', subtitle_shadow_opacity: 0.35,
  subtitle_shadow_size: 2, subtitle_max_chars_per_line: 22, subtitle_max_lines: 2,
  subtitle_cover_enabled: true, subtitle_cover_mode: 'solid', subtitle_cover_blur_strength: 12,
  subtitle_cover_color: '#000000', subtitle_cover_opacity: 0.86,
  subtitle_cover_auto_position: true, subtitle_cover_probe_if_no_ocr: true, subtitle_cover_probe_sample_fps: 1,
  subtitle_cover_height_ratio: 0.12, subtitle_cover_bottom_ratio: 0,
  subtitle_cover_padding_ratio: 0.035, subtitle_cover_lead_seconds: 0.85,
  subtitle_cover_tail_seconds: 0.25, subtitle_cover_radius_ratio: 0.035,
  subtitle_cover_text_y_offset_ratio: 0,
  keep_original_audio: true, add_bgm: true, music_folder: '', favorite_music_paths: [], bgm_volume: 0.16,
  original_audio_volume: 0.85, reduce_original_voice: false, original_voice_reduction_strength: 0.65,
  original_voice_reduction_fallback_volume: 0.35, duck_bgm_when_voice: false, resolution: '1080x1920', fps: 30,
  process_mode: 'all', max_videos: null, selected_video_paths: [], source_selection_id: null,
  batch_performance_mode: 'safe', batch_chunk_size: 50, batch_ffmpeg_timeout_seconds: 900,
  batch_item_timeout_seconds: 1800, batch_watchdog_stale_minutes: 20,
  batch_pause_on_repeated_failures: true, batch_max_consecutive_failures: 10,
  keep_temp: false, review_subtitles_before_render: false,
  auto_render_after_translation: true, auto_mark_low_quality_lines: true, enable_subtitle_rewrite_suggestions: true,
  auto_generate_rewrite_for_flagged_lines: false, auto_apply_safe_rewrites: false, default_rewrite_style: 'short_natural',
  enable_silent_immersive_mode: true, silent_mode_detection: true, silent_mode_strategy: 'chill_immersive',
  detect_speech_presence: true, speech_detection_threshold: 0.35, auto_route_speech_to_voice_reup: true,
  auto_route_no_speech_to_silent_reup: true, auto_route_speech_threshold: 0.28, use_visual_segments_for_silent_video: true,
  silent_segment_duration_min: 1.2, silent_segment_duration_max: 4, generate_visual_captions: true,
  visual_caption_language: 'vi', visual_caption_style: 'natural_short', silent_caption_tone: 'natural',
  generate_voiceover_for_silent_video: false, silent_voiceover_provider: 'edge_tts',
  silent_voiceover_voice: 'vi-VN-HoaiMyNeural', voiceover_auto_slow_video: true,
  voiceover_max_video_slowdown: 1.28, voiceover_comfort_speedup: 1.18,
  keep_immersive_original_audio: true,
  immersive_original_audio_volume: 0.75, add_bgm_for_silent_video: true, immersive_bgm_volume: 0.18,
  silent_review_before_render: true, product_context_lock_enabled: true, locked_product_name: null,
  locked_industry: null, locked_product_keywords: [],
};
