import { Flag, RefreshCw, ShieldAlert } from 'lucide-react';
import type { SubtitleDocumentQualityReport } from '../../types/project';
import GlassButton from '../glass/GlassButton';
import GlassCard from '../glass/GlassCard';

export default function SubtitleQualityPanel({ report, onNextFlagged, onCriticalOnly, onRefresh, busy }: { report: SubtitleDocumentQualityReport | null; onNextFlagged: () => void; onCriticalOnly: () => void; onRefresh: () => void; busy?: boolean }) {
  if (!report) return null;
  const issues = Object.entries(report.issues_breakdown).sort((a, b) => b[1] - a[1]).slice(0, 4);
  return <GlassCard className="p-4" strong><div className="flex items-start justify-between gap-3"><div><div className="text-xs font-semibold uppercase text-slate-500">Chất lượng phụ đề</div><div className="mt-1 text-3xl font-semibold text-white">{Math.round(report.average_score * 100)}%</div></div><ShieldAlert className={report.critical_count ? 'text-rose-300' : 'text-emerald-300'} size={23} /></div><div className="mt-4 grid grid-cols-2 gap-2 text-sm"><Stat label="Cần kiểm tra" value={report.needs_review_count} /><Stat label="Lỗi nặng" value={report.critical_count} /></div>{issues.length ? <div className="mt-4"><div className="text-xs font-semibold uppercase text-slate-500">Lỗi thường gặp</div><div className="mt-2 grid gap-2">{issues.map(([name, count]) => <div className="flex items-center justify-between text-sm" key={name}><span className="text-slate-300">{issueLabel(name)}</span><span className="font-semibold text-slate-100">{count}</span></div>)}</div></div> : null}<div className="mt-4 flex flex-wrap gap-2"><GlassButton className="px-3" variant="secondary" disabled={!report.needs_review_count} onClick={onNextFlagged}><Flag size={15} /> Dòng cần sửa</GlassButton><GlassButton className="px-3" variant="ghost" disabled={!report.critical_count} onClick={onCriticalOnly}>Chỉ lỗi nặng</GlassButton><GlassButton className="px-3" variant="ghost" loading={busy} onClick={onRefresh}><RefreshCw size={15} /> Làm mới</GlassButton></div></GlassCard>;
}
function Stat({ label, value }: { label: string; value: number }) { return <div className="rounded-md bg-black/15 p-3"><div className="text-lg font-semibold text-white">{value}</div><div className="text-xs text-slate-500">{label}</div></div>; }
function issueLabel(value: string) { return ({ too_long: 'Phụ đề quá dài', reading_speed_too_high: 'Tốc độ đọc cao', untranslated_chinese: 'Còn tiếng Trung', ocr_low_confidence: 'OCR chưa chắc chắn', too_many_lines: 'Quá nhiều dòng' } as Record<string, string>)[value] ?? value.replace(/_/g, ' '); }
