import { CalendarClock, Captions, Play } from 'lucide-react';
import { Link } from 'react-router-dom';
import type { SubtitleReviewDocument, SubtitleReviewStatus } from '../../types/project';
import GlassBadge from '../glass/GlassBadge';
import GlassCard from '../glass/GlassCard';
import SubtitleReviewEmptyState from './SubtitleReviewEmptyState';
import { sourceLabel, statusLabel } from './subtitleUi';

export default function SubtitleReviewListPage({ documents, status, saving, onStatus, onRenderApproved }: { documents: SubtitleReviewDocument[]; status: 'all' | SubtitleReviewStatus; saving: boolean; onStatus: (status: 'all' | SubtitleReviewStatus) => void; onRenderApproved: () => void }) {
  const filters: Array<'all' | SubtitleReviewStatus> = ['all', 'pending', 'needs_fix', 'reviewed', 'approved'];
  return <div className="grid gap-4"><GlassCard className="p-4" strong><div className="flex flex-wrap items-center justify-between gap-3"><div className="flex flex-wrap gap-2">{filters.map((item) => <button key={item} className={`rounded-md border px-3 py-2 text-sm font-semibold ${status === item ? 'border-cyan-300/45 bg-cyan-300/12 text-cyan-100' : 'border-white/10 bg-white/5 text-slate-400'}`} type="button" onClick={() => onStatus(item)}>{item === 'all' ? 'Tất cả' : statusLabel(item)}</button>)}</div><button className="inline-flex min-h-10 items-center gap-2 rounded-md border border-white/15 bg-white/8 px-4 py-2 text-sm font-semibold text-white disabled:opacity-50" type="button" disabled={saving || !documents.some((item) => item.status === 'approved')} onClick={onRenderApproved}><Play size={16} /> Render các bản đã duyệt</button></div></GlassCard>{documents.length ? <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{documents.map((item) => <GlassCard className="p-4" hover strong key={item.id}><div className="flex items-start justify-between gap-3"><div className="grid h-10 w-10 shrink-0 place-items-center rounded-md border border-cyan-300/20 bg-cyan-300/8 text-cyan-200"><Captions size={19} /></div><GlassBadge variant={item.status === 'approved' ? 'approved' : item.status === 'needs_fix' ? 'warning' : 'needs_review'}>{statusLabel(item.status)}</GlassBadge></div><h2 className="mt-4 truncate font-semibold text-white" title={fileName(item.video_path)}>{fileName(item.video_path)}</h2><div className="mt-1 text-xs text-slate-500">{sourceLabel(item.source_type)}</div><div className="mt-4 grid grid-cols-3 gap-2 text-center"><Metric label="Dòng" value={item.line_count} /><Metric label="Cần sửa" value={item.quality_needs_review_count} /><Metric label="Lỗi nặng" value={item.quality_critical_count} /></div><div className="mt-4 flex items-center justify-between gap-3"><div className="flex items-center gap-1.5 text-xs text-slate-500"><CalendarClock size={14} />{new Date(item.updated_at).toLocaleString('vi-VN')}</div><Link className="rounded-md border border-cyan-300/50 bg-cyan-300 px-3 py-2 text-xs font-semibold text-slate-950" to={`/subtitle-review/${item.id}`}>Mở review</Link></div></GlassCard>)}</div> : <SubtitleReviewEmptyState />}</div>;
}
function Metric({ label, value }: { label: string; value: number }) { return <div className="rounded-md bg-black/15 px-2 py-2"><div className="font-semibold text-white">{value}</div><div className="mt-1 text-[11px] text-slate-500">{label}</div></div>; }
function fileName(path: string) { return path.split(/[\\/]/).pop() || path; }
