import { AlertTriangle, Sparkles, X } from 'lucide-react';
import type { SubtitleReviewLine, SubtitleRewriteSuggestion } from '../../types/project';
import GlassButton from '../glass/GlassButton';
import { lineText } from './subtitleUi';

export default function SubtitleRewritePanel({ line, suggestions, loading, onApply, onClose }: { line: SubtitleReviewLine | null; suggestions: SubtitleRewriteSuggestion[]; loading: boolean; onApply: (suggestion: SubtitleRewriteSuggestion) => void; onClose: () => void }) {
  if (!line) return null;
  return <section className="glass-card-strong p-5"><div className="flex items-start justify-between gap-3"><div><div className="flex items-center gap-2"><Sparkles className="text-cyan-200" size={18} /><h2 className="font-semibold text-white">Gợi ý rút gọn · Dòng {line.index}</h2></div><p className="mt-1 text-sm text-slate-400">So sánh trước khi áp dụng. Gợi ý có cảnh báo không được tự động áp dụng.</p></div><button className="rounded-md p-2 text-slate-400 hover:bg-white/8 hover:text-white" type="button" onClick={onClose} aria-label="Đóng gợi ý"><X size={18} /></button></div><div className="mt-4 rounded-md border border-white/8 bg-black/15 p-3"><div className="text-xs font-semibold uppercase text-slate-500">Bản hiện tại</div><div className="mt-1 text-sm leading-6 text-slate-200">{lineText(line)}</div></div>{loading ? <div className="mt-4 h-28 animate-pulse rounded-md bg-white/6" /> : suggestions.length ? <div className="mt-4 grid gap-3 lg:grid-cols-2">{suggestions.map((suggestion) => <article className="rounded-md border border-white/10 bg-black/15 p-4" key={suggestion.id}><div className="text-sm font-semibold leading-6 text-white">{suggestion.suggested_text}</div><div className="mt-2 flex flex-wrap gap-3 text-xs text-slate-500"><span>Score {suggestion.quality_score_after == null ? '-' : `${Math.round(suggestion.quality_score_after * 100)}%`}</span><span>{suggestion.char_count_after} ký tự</span><span>CPS {suggestion.estimated_cps_after?.toFixed(1) ?? '-'}</span></div>{suggestion.safety_warnings.length ? <div className="mt-3 flex gap-2 rounded-md border border-amber-300/20 bg-amber-400/8 p-3 text-xs text-amber-100"><AlertTriangle className="shrink-0" size={15} /><div>{suggestion.safety_warnings.join(' · ')}</div></div> : null}<GlassButton className="mt-3 min-h-8 px-3 py-1.5 text-xs" variant={suggestion.safety_warnings.some((item) => item.startsWith('critical:')) ? 'secondary' : 'primary'} onClick={() => onApply(suggestion)}>Áp dụng</GlassButton></article>)}</div> : <div className="mt-4 rounded-md border border-dashed border-white/15 p-6 text-center text-sm text-slate-400">Chưa có gợi ý phù hợp.</div>}</section>;
}
